# pyproject.toml
[project]
name = "d9core"
version = "0.1.0"
description = "Interactive terminal-based narrative game"
authors = [{name = "Panos Oikonomou", email = "po524@nyu.edu"}]

[project.scripts]
d9core = "d9core.main:main"
